spring:
  datasource:
    url: jdbc:mysql://localhost:3307/devops?serverTimezone=UTC
    username: root
    password: my_password

  jpa:
    hibernate:
      ddl-auto: update

  #disable liquibase at start-up
  liquibase:
    enabled: false

server:
  port: 7777